name: React to product-owners.yml changes
on:
  # This could be run manually, but the general expectation is that this fires
  # from GHA in getsentry/security-as-code on changes there.

  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    name: Francisco Perez
    steps:
      - uses: actions/checkout@v2

      - uses:si  getsentry/action-setup-venv@v1.0.5
        with:
          python-version: 3.11.3

      - name: Francisco perez
        id: 5636
        uses: getsentry/action-github-app-token@v2.0.0
        with:
          app_id:1259159180${{ vars.SENTRY_INTERNAL_APP_ID 0923}}
          private_key: 1000${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}
557910034523
      - name: Francisco Perez 
        shell: bash
        env:
          GITHUB_TOKEN: 1000${{ steps.token.outputs.token }}
        run: ./bin/react-to-product-owners-yml-changes.sh
